steps:

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=deployment.yaml
    - --image=gcr.io/solution-kit-11/demo1:v1
    - --location=us-central1-c
    - --cluster=aswini-finalassessment
